/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ClienteControlador;
import Entidades.Cliente;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.property.TextAlignment;
import com.itextpdf.layout.property.UnitValue;
import java.awt.FileDialog;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edith Cruz
 */
public class VistaCliente extends javax.swing.JPanel {

    private final ClienteControlador clienteControlador;
    private Integer id_ClienteSeleccionada = null;

    public VistaCliente() {
        initComponents();
        this.clienteControlador = new ClienteControlador();
        cargarDatosTabla();
    }

    public void cargarDatosTabla() {

        List<Cliente> cliente = clienteControlador.obtenerTodosCliente();

        if (cliente != null) {
            DefaultTableModel model = (DefaultTableModel) tablaCliente.getModel();
            model.setRowCount(0);

            for (Cliente cli : cliente) {
                Object[] row = {
                    cli.getId_Cliente(),
                    cli.getNombre1(),
                    cli.getNombre2(),
                    cli.getApellido1(),
                    cli.getApellido2(),
                    cli.getDireccion(),
                    cli.getTelefono()
                };
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textNombre1 = new javax.swing.JTextField();
        textNombre2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textApellido2 = new javax.swing.JTextField();
        textApellido1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textTelefono = new javax.swing.JTextField();
        textBuscar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpliar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nombre1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, -1, -1));

        textNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombre1ActionPerformed(evt);
            }
        });
        jPanel1.add(textNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 22, 161, 30));
        jPanel1.add(textNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 64, 161, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 70, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Apellido1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 28, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Apellido2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 70, -1, -1));
        jPanel1.add(textApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 64, 160, 30));
        jPanel1.add(textApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 22, 160, 30));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Direccion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 28, -1, -1));
        jPanel1.add(textDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 22, 178, 30));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Telefono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 70, -1, -1));
        jPanel1.add(textTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 64, 178, 30));

        textBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textBuscarcampotextoBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(textBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 330, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Buscar");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 66, -1));

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Cliente", "Nombre1", "Nombre2", "Apellido1", "Apellido2", "Direccion", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCliente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 576, 250));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardaraccionBotonGuardar(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, 34));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaraccionBotonEliminar(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 118, 34));

        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizaraccionBotonActualizar(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 120, 34));

        btnLimpliar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpliar.setText("Limpiar");
        btnLimpliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpliaraccionBotonLimpiar(evt);
            }
        });
        jPanel1.add(btnLimpliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 116, 34));

        jButton1.setText("Generar Reportes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionBotonGenerarReportes(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombre1ActionPerformed

    private void textBuscarcampotextoBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBuscarcampotextoBuscarKeyTyped
        String textoBusqueda = textBuscar.getText().trim().toLowerCase();
        List<Cliente> cliente = clienteControlador.obtenerTodosCliente();

        DefaultTableModel modelo = (DefaultTableModel) tablaCliente.getModel();
        modelo.setRowCount(0);

        if (cliente != null) {
            for (Cliente cli : cliente) {
                if (textoBusqueda.isEmpty()
                        || cli.getNombre1().toLowerCase().contains(textoBusqueda)
                        || cli.getNombre2().toLowerCase().contains(textoBusqueda)
                        || cli.getApellido1().toLowerCase().contains(textoBusqueda)
                        || cli.getApellido2().toLowerCase().contains(textoBusqueda)
                        || cli.getDireccion().toLowerCase().contains(textoBusqueda)
                        || cli.getTelefono().toLowerCase().contains(textoBusqueda)) {

                    Object[] fila = {
                        cli.getId_Cliente(),
                        cli.getNombre1(),
                        cli.getNombre2(),
                        cli.getApellido1(),
                        cli.getApellido2(),
                        cli.getDireccion(),
                        cli.getTelefono()
                    };
                    modelo.addRow(fila);
                }
            }
        }
    }//GEN-LAST:event_textBuscarcampotextoBuscarKeyTyped

    private void tablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClienteMouseClicked
        if (evt.getClickCount() == 2) {

            int filaSeleccionada = tablaCliente.getSelectedRow();

            if (filaSeleccionada != -1) {

                id_ClienteSeleccionada = (int) tablaCliente.getValueAt(filaSeleccionada, 0);
                String Nombre1 = (String) tablaCliente.getValueAt(filaSeleccionada, 1);
                String Nombre2 = (String) tablaCliente.getValueAt(filaSeleccionada, 2);
                String Apellido1 = (String) tablaCliente.getValueAt(filaSeleccionada, 3);
                String Apellido2 = (String) tablaCliente.getValueAt(filaSeleccionada, 4);
                String Direccion = (String) tablaCliente.getValueAt(filaSeleccionada, 5);
                String Telefono = (String) tablaCliente.getValueAt(filaSeleccionada, 6);

                textNombre1.setText(Nombre1);
                textNombre2.setText(Nombre2);
                textApellido1.setText(Apellido1);
                textApellido2.setText(Apellido2);
                textDireccion.setText(Direccion);
                textTelefono.setText(Telefono);

                btnEliminar.setEnabled(false);
                btnGuardar.setEnabled(false);

            }
        }
    }//GEN-LAST:event_tablaClienteMouseClicked

    private void btnGuardaraccionBotonGuardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardaraccionBotonGuardar
        String Nombre1 = textNombre1.getText();
        String Nombre2 = textNombre2.getText();
        String Apellido1 = textApellido1.getText();
        String Apellido2 = textApellido2.getText();
        String Direccion = textDireccion.getText();
        String Telefono = textTelefono.getText();

        if (!Nombre1.isEmpty() && !Nombre2.isEmpty() && !Apellido1.isEmpty() && !Apellido2.isEmpty() && !Direccion.isEmpty()
                && !Telefono.isEmpty()) {
            clienteControlador.crearCliente(Nombre1, Nombre2, Apellido1, Apellido2, Direccion, Telefono);
            cargarDatosTabla();

            textNombre1.setText("");
            textNombre2.setText("");
            textApellido1.setText("");
            textApellido2.setText("");
            textDireccion.setText("");
            textTelefono.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llene los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardaraccionBotonGuardar

    private void btnEliminaraccionBotonEliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaraccionBotonEliminar
        int filaSeleccionada = tablaCliente.getSelectedRow();
        if (filaSeleccionada != -1) {
            int id_Cliente = (int) tablaCliente.getValueAt(filaSeleccionada, 0);
            clienteControlador.eliminarCliente(id_Cliente);
            cargarDatosTabla();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.", "error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminaraccionBotonEliminar

    private void btnActualizaraccionBotonActualizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizaraccionBotonActualizar
        String Nombre1 = textNombre1.getText();
        String Nombre2 = textNombre2.getText();
        String Apellido1 = textApellido1.getText();
        String Apellido2 = textApellido2.getText();
        String Direccion = textDireccion.getText();
        String Telefono = textTelefono.getText();

        if (!Nombre1.isEmpty() && !Nombre2.isEmpty() && !Apellido1.isEmpty() && !Apellido2.isEmpty() && !Direccion.isEmpty()
                && !Telefono.isEmpty()) {

            clienteControlador.actualizarCliente(id_ClienteSeleccionada, Nombre1, Nombre2, Apellido1, Apellido2, Direccion, Telefono);
            cargarDatosTabla();

            textNombre1.setText(Nombre1);
            textNombre2.setText(Nombre2);
            textApellido1.setText(Apellido1);
            textApellido2.setText(Apellido2);
            textDireccion.setText(Direccion);
            textTelefono.setText(Telefono);
            id_ClienteSeleccionada = null;

            btnEliminar.setEnabled(true);
            btnGuardar.setEnabled(true);

        } else {

            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llene los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnActualizaraccionBotonActualizar

    private void btnLimpliaraccionBotonLimpiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpliaraccionBotonLimpiar
        textNombre1.setText("");
        textNombre2.setText("");
        textApellido1.setText("");
        textApellido2.setText("");
        textDireccion.setText("");
        textTelefono.setText("");
        btnEliminar.setEnabled(true);
        btnGuardar.setEnabled(true);
        cargarDatosTabla(); // Reload
    }//GEN-LAST:event_btnLimpliaraccionBotonLimpiar

    private void AccionBotonGenerarReportes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionBotonGenerarReportes
        try {
            FileDialog dialogoArchivo = new FileDialog((java.awt.Frame) null, "Guardar Reporte PDF", FileDialog.SAVE);
            dialogoArchivo.setFile("ReporteCategorias.pdf");
            dialogoArchivo.setVisible(true);

            String ruta = dialogoArchivo.getDirectory();
            String nombreArchivo = dialogoArchivo.getFile();

            if (ruta == null || nombreArchivo == null) {
                JOptionPane.showMessageDialog(this, "Operación cancelada", "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            String rutaCompleta = ruta + nombreArchivo;
            PdfWriter escritor = new PdfWriter(rutaCompleta);
            PdfDocument pdf = new PdfDocument(escritor);
            Document documento = new Document(pdf);

            documento.add(new Paragraph("Reporte de Categoria")
                    .setTextAlignment(TextAlignment.CENTER)
                    .setFontSize(20)
                    .setBold());

            documento.add(new Paragraph("Fwxha:" + new java.util.Date().toString())
                    .setTextAlignment(TextAlignment.CENTER)
                    .setFontSize(12));

            Table tabla = new Table(3);
            tabla.setWidth(UnitValue.createPercentValue(100));
            tabla.addHeaderCell("ID Cliente").setBold();
            tabla.addHeaderCell("Nombre1").setBold();
            tabla.addHeaderCell("Nombre2").setBold();
            tabla.addHeaderCell("Apellido1").setBold();
            tabla.addHeaderCell("Apellido2").setBold();
            tabla.addHeaderCell("Direccion").setBold();
            tabla.addHeaderCell("Telefono").setBold();

            List<Cliente> listaCliente
                    = clienteControlador.obtenerTodosCliente();
            if (listaCliente != null) {
                for (Cliente cli : listaCliente) {
                    tabla.addCell(String.valueOf(cli.getId_Cliente()));
                    tabla.addCell(cli.getNombre1());
                    tabla.addCell(cli.getNombre2());
                    tabla.addCell(cli.getApellido1());
                    tabla.addCell(cli.getApellido2());
                    tabla.addCell(cli.getDireccion());
                    tabla.addCell(cli.getTelefono());
                }
            }

            documento.add(tabla);

            documento.add(new Paragraph("Notas: Reporte generado automáticamente desde el sistema.")
                    .setFontSize(10)
                    .setMarginTop(20));

            documento.close();

            JOptionPane.showMessageDialog(
                    this,
                    "Reporte PDF generado con éxito en: " + rutaCompleta,
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    this,
                    "Error al generar el PDF:" + e.getMessage(),
                    "Error ", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_AccionBotonGenerarReportes


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpliar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTextField textApellido1;
    private javax.swing.JTextField textApellido2;
    private javax.swing.JTextField textBuscar;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textNombre1;
    private javax.swing.JTextField textNombre2;
    private javax.swing.JTextField textTelefono;
    // End of variables declaration//GEN-END:variables
}
