/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ProveedorControlador;
import Entidades.Proveedor;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.property.TextAlignment;
import com.itextpdf.layout.property.UnitValue;
import java.awt.FileDialog;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Welvin
 */
public class VistaProveedor extends javax.swing.JPanel {

    private final ProveedorControlador proveedorControlador;
    private Integer id_ProveedorSeleccionada = null;

    /**
     * Creates new form VistaProveedor
     */
    public VistaProveedor() {
        initComponents();
        this.proveedorControlador = new ProveedorControlador();
        cargarDatosTabla();
    }

    public void cargarDatosTabla() {

        List<Proveedor> proveedor = proveedorControlador.obtenerTodosProveedores();

        if (proveedor != null) {
            DefaultTableModel model = (DefaultTableModel) tablaProveedor.getModel();
            model.setRowCount(0);

            for (Proveedor prov : proveedor) {
                Object[] row = {
                    prov.getId_Proveedor(),
                    prov.getNombre_Proveedor(),
                    prov.getTelefono(),
                    prov.getTipo_distribuidor()
                };
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textNombre_Proveedor = new javax.swing.JTextField();
        textTelefono = new javax.swing.JTextField();
        textTipo_distribuidor = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        textBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedor = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Proveedor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Telefono");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tipo distribuidor");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 142, -1, -1));

        textNombre_Proveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(textNombre_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 30, 173, 31));

        textTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(textTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 84, 168, 30));

        textTipo_distribuidor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(textTipo_distribuidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 173, 31));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 51, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardaraccionBotonGuardar(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 83, 121, 31));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Datos Proveedor");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 6, 140, -1));

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 51, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiaraccionBotonLimpiar(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 83, 119, 32));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaraccionBotonEliminar(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 120, 31));

        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 51, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizaraccionBotonActualizar(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 120, 31));

        textBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campotextBuscarKeyTyped(evt);
            }
        });
        jPanel1.add(textBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 360, 30));

        tablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre Proveedor", "Telefono", "Tipo distribuidor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProveedor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tablaProveedorMouseMoved(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProveedor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 180, 680, 220));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("Editar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1accionBotonEditar(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 122, 34));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 255));
        jButton2.setText("Generar Reporte");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionBotonReporte(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/291474364_116090381133197_1246855093686710006_n (1)-Photoroom (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, -350, 1100, 1150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTelefonoActionPerformed

    private void btnGuardaraccionBotonGuardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardaraccionBotonGuardar
        String Nombre = textNombre_Proveedor.getText();
        String Telefono = textTelefono.getText();
        String Tipo = textTipo_distribuidor.getText();

        if (!Nombre.isEmpty() && !Telefono.isEmpty() && !Tipo.isEmpty()) {
            proveedorControlador.crearProveedor(Nombre, Telefono, Tipo);
            cargarDatosTabla();

            textNombre_Proveedor.setText("");
            textTelefono.setText("");
            textTipo_distribuidor.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llene los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardaraccionBotonGuardar

    private void btnLimpiaraccionBotonLimpiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiaraccionBotonLimpiar
        textNombre_Proveedor.setText("");
        textTelefono.setText("");
        textTipo_distribuidor.setText("");
        btnEliminar.setEnabled(true);
        btnGuardar.setEnabled(true);
        cargarDatosTabla(); // Reload
    }//GEN-LAST:event_btnLimpiaraccionBotonLimpiar

    private void btnEliminaraccionBotonEliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaraccionBotonEliminar
        int filaSeleccionada = tablaProveedor.getSelectedRow();
        if (filaSeleccionada != -1) {
            int id_Proveedor = (int) tablaProveedor.getValueAt(filaSeleccionada, 0);
            proveedorControlador.eliminarProveedor(id_Proveedor);
            cargarDatosTabla();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.", "error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminaraccionBotonEliminar

    private void btnActualizaraccionBotonActualizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizaraccionBotonActualizar
        String Nombre = textNombre_Proveedor.getText();
        String Telefono = textTelefono.getText();
        String Tipo = textTipo_distribuidor.getText();

        if (!Nombre.isEmpty() && !Telefono.isEmpty() && !Tipo.isEmpty()) {

            proveedorControlador.actualizarProveedor(id_ProveedorSeleccionada, Nombre, Telefono, Tipo);
            cargarDatosTabla();

            textNombre_Proveedor.setText("");
            textTelefono.setText("");
            textTipo_distribuidor.setText("");
            id_ProveedorSeleccionada = null;

            btnEliminar.setEnabled(true);
            btnGuardar.setEnabled(true);

        } else {

            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llene los campos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnActualizaraccionBotonActualizar

    private void campotextBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campotextBuscarKeyTyped
        String textoBusqueda = textBuscar.getText().trim().toLowerCase();
        List<Proveedor> proveedor = proveedorControlador.obtenerTodosProveedores();

        DefaultTableModel modelo = (DefaultTableModel) tablaProveedor.getModel();
        modelo.setRowCount(0);

        if (proveedor != null) {
            for (Proveedor prov : proveedor) {
                if (textoBusqueda.isEmpty()
                        || prov.getNombre_Proveedor().toLowerCase().contains(textoBusqueda)
                        || prov.getTelefono().toLowerCase().contains(textoBusqueda)
                        || prov.getTipo_distribuidor().toLowerCase().contains(textoBusqueda)) {

                    Object[] fila = {
                        prov.getNombre_Proveedor(),
                        prov.getTelefono(),
                        prov.getTipo_distribuidor()
                    };
                    modelo.addRow(fila);
                }
            }
        }
    }//GEN-LAST:event_campotextBuscarKeyTyped

    private void tablaProveedorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProveedorMouseMoved
        if (evt.getClickCount() == 2) {

            int filaSeleccionada = tablaProveedor.getSelectedRow();

            if (filaSeleccionada != -1) {

                id_ProveedorSeleccionada = (int) tablaProveedor.getValueAt(filaSeleccionada, 0);
                String Nombre = (String) tablaProveedor.getValueAt(filaSeleccionada, 1);
                String Telefono = (String) tablaProveedor.getValueAt(filaSeleccionada, 2);
                String Tipo = (String) tablaProveedor.getValueAt(filaSeleccionada, 3);

                textNombre_Proveedor.setText(Nombre);
                textTelefono.setText(Telefono);
                textTipo_distribuidor.setText(Tipo);

                btnEliminar.setEnabled(false);
                btnGuardar.setEnabled(false);

            }
        }
    }//GEN-LAST:event_tablaProveedorMouseMoved

    private void jButton1accionBotonEditar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1accionBotonEditar
        int filaSeleccionada = tablaProveedor.getSelectedRow();
        if (filaSeleccionada != -1) {
            // Guardamos el ID del cliente seleccionado
            id_ProveedorSeleccionada = (Integer) tablaProveedor.getValueAt(filaSeleccionada, 0);

            // Obtenemos los datos de esa fila
            String Nombre = (String) tablaProveedor.getValueAt(filaSeleccionada, 1);
            String Telefono = (String) tablaProveedor.getValueAt(filaSeleccionada, 2);
            String Tipo = (String) tablaProveedor.getValueAt(filaSeleccionada, 3);

            // Cargamos esos datos en los campos de texto
            textNombre_Proveedor.setText(Nombre);
            textTelefono.setText(Telefono);
            textTipo_distribuidor.setText(Tipo);

            // Ajustamos los botones:
            // deshabilitamos Guardar y Eliminar, y activamos Actualizar
            btnGuardar.setEnabled(false);
            btnEliminar.setEnabled(false);
            btnActualizar.setEnabled(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Selecciona una fila para editar.",
                    "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_jButton1accionBotonEditar

    private void accionBotonReporte(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionBotonReporte
        try {
            FileDialog dialogoArchivo = new FileDialog((java.awt.Frame) null, "Guardar Reporte PDF", FileDialog.SAVE);
            dialogoArchivo.setFile("ReporteProveedor.pdf");
            dialogoArchivo.setVisible(true);

            String ruta = dialogoArchivo.getDirectory();
            String nombreArchivo = dialogoArchivo.getFile();

            if (ruta == null || nombreArchivo == null) {
                JOptionPane.showMessageDialog(this, "Operación cancelada", "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            String rutaCompleta = ruta + nombreArchivo;
            PdfWriter escritor = new PdfWriter(rutaCompleta);
            PdfDocument pdf = new PdfDocument(escritor);
            Document documento = new Document(pdf);

            documento.add(new Paragraph("Reporte de Proveedor")
                    .setTextAlignment(TextAlignment.CENTER)
                    .setFontSize(20)
                    .setBold());

            documento.add(new Paragraph("Fwxha:" + new java.util.Date().toString())
                    .setTextAlignment(TextAlignment.CENTER)
                    .setFontSize(12));

            Table tabla = new Table(3);
            tabla.setWidth(UnitValue.createPercentValue(100));
            tabla.addHeaderCell("ID Proveedor").setBold();
            tabla.addHeaderCell("Nombre").setBold();
            tabla.addHeaderCell(" Telefono").setBold();
            tabla.addHeaderCell("Tipo_distribuidor").setBold();

            List<Proveedor> listaProveedor
                    = proveedorControlador.obtenerTodosProveedores();
            if (listaProveedor != null) {
                for (Proveedor prove : listaProveedor) {
                    tabla.addCell(String.valueOf(prove.getId_Proveedor()));
                    tabla.addCell(prove.getNombre_Proveedor());
                    tabla.addCell(prove.getTelefono());
                    tabla.addCell(prove.getTipo_distribuidor());

                }
            }

            documento.add(tabla);

            documento.add(new Paragraph("Notas: Reporte generado automáticamente desde el sistema.")
                    .setFontSize(10)
                    .setMarginTop(20));

            documento.close();

            JOptionPane.showMessageDialog(
                    this,
                    "Reporte PDF generado con éxito en: " + rutaCompleta,
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    this,
                    "Error al generar el PDF:" + e.getMessage(),
                    "Error ", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_accionBotonReporte


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProveedor;
    private javax.swing.JTextField textBuscar;
    private javax.swing.JTextField textNombre_Proveedor;
    private javax.swing.JTextField textTelefono;
    private javax.swing.JTextField textTipo_distribuidor;
    // End of variables declaration//GEN-END:variables
}
