/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ProductoControlador;
import Entidades.Producto;
import DAO.DAOProducto;
import java.sql.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.Date;

import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.property.TextAlignment;
import com.itextpdf.layout.property.UnitValue;
import java.awt.FileDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author D23
 */
public class VistaProductoss extends javax.swing.JPanel {
private Integer id_productoSeleccionada = null;
   private final ProductoControlador controladorProducto;

    /**
     * Creates new form VistaProducto
     */
    public VistaProductoss() {
        initComponents();
        this.controladorProducto = new ProductoControlador();
        cargarDatosTabla();
    }

    private void cargarDatosTabla() {
    // Obtener todas las categorías del controlador
    List<Producto> productos = controladorProducto.obtenerTodosProductos();
    if (productos != null) {
        // Obtener el modelo existente de la tabla con un casting adecuado
        DefaultTableModel model = (DefaultTableModel) tablaProductos.getModel();

        // Limpiar las filas existentes
        model.setRowCount(0);

        // Llenar las filas con los datos de los productos
        for (Producto pro : productos) {
            Object[] row = {
                pro.getId_producto(),
                pro.getNombre_prod(),
                pro.getTipo_Prod(),
                pro.getExistencia_Prod(),
                pro.getPrecio_Costo(),
                pro.getPrecio_Venta(),
                pro.getFe_caducidad()
            };
            model.addRow(row);
        }
    }
}
private void limpiar() {
        textNombreProducto.setText("");
        TextTipoproducto.setText("");
        TextExistencia.setText("");
        TextPrecioCosto.setText("");
        TextPrecioVenta.setText("");
        TextBuscador.setText("");
        id_productoSeleccionada = null;
        selectorfechaProducto.setDate(new Date());
        btnBorrar.setEnabled(true);
        btnLimpiar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextPrecioVenta = new javax.swing.JTextField();
        TextBuscador = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        TextPrecioCosto = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        selectorfechaProducto = new com.toedter.calendar.JDateChooser();
        jTextField1 = new javax.swing.JTextField();
        ReporteProducto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        textNombreProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TextTipoproducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextExistencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setText("Almacen Rural");

        jLabel4.setText("Precio  Venta");

        TextBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextBuscadorKeyTyped(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(204, 0, 51));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(204, 0, 51));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(204, 0, 51));
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(204, 0, 51));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        tablaProductos.setBackground(new java.awt.Color(255, 204, 204));
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Tipo", "Existencia", "Precio Costo", "Precio Venta", "Fecha_caducidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        jLabel7.setText("Precio  Costo");

        btnLimpiar.setBackground(new java.awt.Color(204, 0, 51));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(255, 204, 204));

        ReporteProducto.setBackground(new java.awt.Color(255, 153, 153));
        ReporteProducto.setText("Reporte");
        ReporteProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteProductoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setText("Datos de Producto");

        jLabel1.setText("Nombre ");

        jLabel3.setText("Existencia");

        jLabel2.setText("Tipo");

        jLabel5.setText("Fecha de Caducidad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textNombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(TextTipoproducto)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(30, 30, 30)
                                    .addComponent(TextExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel5)))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextTipoproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectorfechaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(TextPrecioCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(445, 445, 445)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1198, 1198, 1198)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(22, 22, 22)
                        .addComponent(ReporteProducto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TextPrecioCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(206, 206, 206)
                            .addComponent(TextPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(172, 172, 172)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(jLabel6))
                                        .addComponent(ReporteProducto))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(28, 28, 28)
                                                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(60, 60, 60)
                                                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(106, 106, 106)
                                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(10, 10, 10)
                                    .addComponent(TextBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(selectorfechaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
         Date fecha = this.selectorfechaProducto.getDate();
        java.sql.Date fecha_Caducidad = new java.sql.Date(fecha.getTime());
        String nombre_produ = textNombreProducto.getText();
        String tipo_produ = TextTipoproducto.getText();
        double cantidad_existente = Double.parseDouble(TextExistencia.getText());
        double precio_costo = Double.parseDouble(TextPrecioCosto.getText());
        double precio_venta = Double.parseDouble(TextPrecioVenta.getText());
        if (!nombre_produ.isEmpty() && !tipo_produ.isEmpty()) {
            try {
            
                controladorProducto.crearProducto(nombre_produ, tipo_produ, cantidad_existente,
                        precio_costo, precio_venta, fecha_Caducidad);
                cargarDatosTabla();
            }catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
             }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Llene los campos requeridos. ", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

     
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

       int filaSeleccionada = tablaProductos.getSelectedRow();

    if (filaSeleccionada != -1) {
        try {
            // Assuming the ID is stored in column index 0
            Object idObject = tablaProductos.getValueAt(filaSeleccionada, 0);
            int id_producto = Integer.parseInt(idObject.toString()); // Safe conversion

            // Delete the product
            controladorProducto.eliminarProducto(id_producto);
            cargarDatosTabla();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al obtener el ID del producto.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    
}
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void TextBuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextBuscadorKeyTyped
        
       String TextBuscar = TextBuscador.getText().trim().toLowerCase();
    
    // Obtener la lista de productos
    List<Producto> productos = controladorProducto.obtenerTodosProductos();
    DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
    modelo.setRowCount(0);

    if (productos != null) {
        for (Producto pro : productos) {
            
            // Verificar si el producto coincide con el filtro de búsqueda
            if (TextBuscar.isEmpty() || 
                pro.getNombre_prod().toLowerCase().contains(TextBuscar) ||
                pro.getTipo_Prod().toLowerCase().contains(TextBuscar) ||
                String.valueOf(pro.getExistencia_Prod()).contains(TextBuscar) ||
                String.valueOf(pro.getPrecio_Costo()).contains(TextBuscar) ||
                String.valueOf(pro.getPrecio_Venta()).contains(TextBuscar)) {

                // Agregar producto a la tabla si coincide
                Object[] fila = {
                    pro.getId_producto(),
                    pro.getNombre_prod(),
                    pro.getTipo_Prod(),
                    pro.getExistencia_Prod(),
                    pro.getPrecio_Costo(),
                    pro.getPrecio_Venta(),
                    pro.getFe_caducidad()
                };
                modelo.addRow(fila);
            }
        }
    }
    }//GEN-LAST:event_TextBuscadorKeyTyped

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        // TODO add your handling code here:
            if (evt.getClickCount() == 2) {
            int filaSeleccionada = tablaProductos.getSelectedRow();
            if (filaSeleccionada != -1) {
        
                    id_productoSeleccionada = (int) tablaProductos.getValueAt(filaSeleccionada, 0);
                    String nombre_produ = tablaProductos.getValueAt(filaSeleccionada, 1).toString();
                    String tipo_produ = tablaProductos.getValueAt(filaSeleccionada, 2).toString();
                    double cantidad_existente = Double.parseDouble(tablaProductos.getValueAt(filaSeleccionada, 3).toString());
                    double precio_Costo = Double.parseDouble(tablaProductos.getValueAt(filaSeleccionada, 4).toString());
                    double precio_Venta = Double.parseDouble(tablaProductos.getValueAt(filaSeleccionada, 5).toString());
                    Date fecha = (Date) tablaProductos.getValueAt(filaSeleccionada, 6);

                    // Asignar valores a los campos de texto, convirtiéndolos a String
                    textNombreProducto.setText(nombre_produ);
                    TextTipoproducto.setText(tipo_produ);
                    TextExistencia.setText(String.valueOf(cantidad_existente));
                    TextPrecioCosto.setText(String.valueOf(precio_Costo));
                    TextPrecioVenta.setText(String.valueOf(precio_Venta));
                    selectorfechaProducto.setDate(fecha);
                    btnBorrar.setEnabled(false);
                    btnGuardar.setEnabled(false);
                }
        }
    }//GEN-LAST:event_tablaProductosMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:                                             
    String nombre_produ = textNombreProducto.getText();
    String tipo_produ = TextTipoproducto.getText();

   
        double cantidad_existente = Double.parseDouble(TextExistencia.getText());
        double precio_Costo = Double.parseDouble(TextPrecioCosto.getText());
        double precio_Venta = Double.parseDouble(TextPrecioVenta.getText());
        Date fecha = this.selectorfechaProducto.getDate();
        java.sql.Date fecha_Caducidad = new java.sql.Date(fecha.getTime());
         if (id_productoSeleccionada != null && !nombre_produ.isEmpty() && !tipo_produ.isEmpty()) {
            try {
                controladorProducto.actualizarProducto(id_productoSeleccionada, nombre_produ, tipo_produ, cantidad_existente, precio_Costo,
                        precio_Venta, fecha_Caducidad);
                cargarDatosTabla();
                limpiar();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            }else {
javax. swing. JOptionPane. showMessageDialog(this, "Llene los campos obligatorios.", "Error", javax. swing.JOptionPane.ERROR_MESSAGE);

        }


    

// Método para limpiar los campos después de actualizar

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
limpiar();       // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void ReporteProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteProductoActionPerformed
        // TODO add your handling code here:
        try {
            FileDialog dialogoArchivo = new FileDialog((java.awt.Frame) null, "Guardar reporte PDF", FileDialog.SAVE);
            dialogoArchivo.setFile("ReporteProducto.pdf");
            dialogoArchivo.setVisible(true);

            String ruta = dialogoArchivo.getDirectory();
            String nombreArchivo = dialogoArchivo.getFile();

            if (ruta == null || nombreArchivo == null) {
                JOptionPane.showMessageDialog(this, "Opteracion cancelada.", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            String rutaCompleta = ruta + nombreArchivo;

            PdfWriter escritor = new PdfWriter(rutaCompleta);
            PdfDocument pdf = new PdfDocument(escritor);
            Document documento = new Document(pdf);

            documento.add(new Paragraph("Reporte deProducto")
                    .setTextAlignment(TextAlignment.CENTER)
                    .setFontSize(20)
                    .setBold());

            documento.add(new Paragraph("Fecha:" + new java.util.Date().toString())
                    .setTextAlignment(TextAlignment.CENTER)
                    .setFontSize(12));

            Table tabla = new Table(7);
            tabla.setWidth(UnitValue.createPercentValue(100));
            tabla.addHeaderCell("ID Producto").setBold();
            tabla.addHeaderCell("Nombre").setBold();
            tabla.addHeaderCell("Tipo").setBold();
            tabla.addHeaderCell("Existencia").setBold();
            tabla.addHeaderCell("Precio Costo").setBold();
            tabla.addHeaderCell("Precio Venta").setBold();
            tabla.addHeaderCell("Fecha Caducidad").setBold();

            List<Producto> listaProducto = controladorProducto.obtenerTodosProductos();
            if (listaProducto != null) {
                for (Producto producto : listaProducto) {
                    tabla.addCell(String.valueOf(producto.getId_producto()));
                    tabla.addCell(producto.getNombre_prod());
                    tabla.addCell(producto.getTipo_Prod());
                    tabla.addCell(String.valueOf(producto.getExistencia_Prod()));
                    tabla.addCell(String.valueOf(producto.getPrecio_Costo()));
                    tabla.addCell(String.valueOf(producto.getPrecio_Venta()));
                    tabla.addCell(String.valueOf(producto.getFe_caducidad()));
                }

            }

            documento.add(tabla);

            documento.add(new Paragraph("Notas: Reporte generado automaticamente desde el sistema")
                    .setFontSize(10)
                    .setMarginTop(28));

            documento.close();
            JOptionPane.showMessageDialog(
                    this,
                    "Reporte PDF Generado con exito en : " + rutaCompleta,
                    "Exito", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al generar el PDF:" + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ReporteProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReporteProducto;
    private javax.swing.JTextField TextBuscador;
    private javax.swing.JTextField TextExistencia;
    private javax.swing.JTextField TextPrecioCosto;
    private javax.swing.JTextField TextPrecioVenta;
    private javax.swing.JTextField TextTipoproducto;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private com.toedter.calendar.JDateChooser selectorfechaProducto;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField textNombreProducto;
    // End of variables declaration//GEN-END:variables
}
